const express=require('express'), multer=require('multer'), path=require('path'), fs=require('fs');
const auth=require('../controllers/authController'), products=require('../controllers/productController');
const ops=require('../controllers/operationController'), admin=require('../controllers/adminController');
const {requireAuth,requireRole}=require('../middleware/auth');
const r=express.Router(), uploadDir=path.resolve('public/uploads');
fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(q,f,cb)=>cb(null,`qr-${Date.now()}${path.extname(f.originalname).toLowerCase()}`)}),limits:{fileSize:2e6},fileFilter:(q,f,cb)=>cb(null,f.mimetype.startsWith('image/'))});
r.post('/auth/login',auth.login);r.get('/auth/me',auth.me);r.post('/auth/logout',auth.logout);
r.use(requireAuth);
r.get('/products',products.list);r.get('/products/barcode/:code',products.barcode);
r.get('/meta',products.meta);r.post('/sales',ops.sale);r.get('/sales',ops.sales);
r.get('/config',admin.config);
r.use(requireRole('administrador'));
r.post('/products',products.save);r.put('/products/:id',products.update);r.post('/products/:id/adjust',products.adjust);
r.post('/meta/:type',products.addMeta);r.get('/movements',ops.movements);r.post('/purchases',ops.purchase);
r.get('/dashboard',admin.dashboard);r.get('/suppliers',admin.suppliers);r.post('/suppliers',admin.saveSupplier);
r.get('/users',admin.users);r.post('/users',admin.saveUser);r.post('/config/qr',upload.single('qr'),admin.qr);
module.exports=r;
